### ISSUE TITLE
Store images

### ISSUE THREAD

**Issue by dreamflasher** [iansinnott/full-text-tabs-forever#5]
Does FTTF store websites with their images or only text? 
If it does not already store images, consider this a feature request :)

Thanks for your great work!

**Comment by iansinnott** [comment]
Hey @dreamflasher, welcome. It currently does not store images. How would you use this functionality? 

The purpose of the extension is to allow you to search past websites. How would you search for images? Were you thinking the extension would run OCR on the images to make them searchable?

**Comment by iansinnott** [comment]
Yeah, that makes sense. However for this use case I think [ArchiveBox] is a more suitable project. It does a great job of preserving everything and can make single-file backups of a website. I myself use it in addition to FTTF for when I want to archive a webpage. FTTF is more focused on search rather than archival.

Going to close this for now as unplanned. Open to suggestions though, if you or anyone else thinks that there's something interesting we could be doing with page images.

[ArchiveBox]: https://github.com/ArchiveBox/ArchiveBox/
